sudo: false
cache: pip

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml

language: python

python:
  - "3.5"

env:
  global:
    - VERSION="12.0" TESTS="0" LINT_CHECK="0"
  matrix:
    - LINT_CHECK="1"
    # Exclusion because of conflict with odoo 'product_expiry' module
    - TESTS="1" ODOO_REPO="odoo/odoo" MAKEPOT="1" EXCLUDE="product_expiry_simple"
    - TESTS="1" ODOO_REPO="OCA/OCB" EXCLUDE="product_expiry_simple"
    - TESTS="1" ODOO_REPO="OCA/OCB" EXCLUDE="product_expiry,stock_move_quick_lot"

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git $HOME/maintainer-quality-tools
  - export PATH=$HOME/maintainer-quality-tools/travis:$PATH
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
